### ISSUE TITLE
Issue with escaping

### ISSUE THREAD

**Issue by ghislainfourny** [Sparksoniq/sparksoniq#119]
This doesn't work quite right on the shell.

"This is a newline\nand an escaped \\"quote\\"."

**Comment by CanBerker** [comment]
@ghislainfourny 
Should the following line:
> "This is a newline\nand an escaped "quote"."
be of the format:
> "This is a newline\nand an escaped \"quote\"."

If not, could you elaborate ?

**Comment by ghislainfourny** [comment]
You are correct!

**Comment by ghislainfourny** [comment]
After investigating: there is nothing wrong with the lexer.

The issue is with the JLines shell, which interprets \ as escaping sequences before the query reaches Sparksoniq. We should see if we can deactivate this and forward the raw input to the engine.
