### ISSUE TITLE
Wrong result for count(json-file("...").some_array[])

### ISSUE THREAD

**Issue by ingomueller-net** [Sparksoniq/sparksoniq#135]
This is a small variation of #70, which isn't fixed yet. The following query returns a wrong result if the input file has more than 100 rows:
```xquery
count(json-file("/tmp/orders.jsonl").items[])
```
The produced result is the same as if run on the first 100 rows of the file, so I suppose that some postprocessing happens in the driver, which doesn't get the whole intermediate result from the cluster.

Also, this variation is borken:
```xquery
for $i in json-file("/tmp/orders.jsonl").items[]
group by $prod := $i.product
return {"prod":$prod, "quant": sum($i.quantity) div count($i)}
```
The tuples seen by the FLOWR expression are only those produced by the first 100 lines of the input.

**Comment by ingomueller-net** [comment]
Further variants reported by a student:

When I enter the following query:
```xquery
$ for $i in json-file(“/tmp/orders.jsonl”) $ return $i.order_id
```
I only get the values 0,…, 99 outputted to the screen (even though when I run the query:
```xquery
$ for $i in json-file("/tmp/orders.jsonl") $ where $i.order_id = 6339 $ return $i
```

**Comment by ghislainfourny** [comment]
This is a known issue, due to the fact that object lookup and array unboxing are not pushed down to Spark yet.

In order to make sure it is pushed down to Spark, one must do this instead:

    for $j in json-file("/tmp/orders.jsonl")
    for $i in $j.items[]
    group by $prod := $i.product
    return {"prod":$prod, "quant": sum($i.quantity) div count($i)}

We should also make sure a warning is issued when the data is "truncated" when it can't be pushed down to Spark.

**Comment by CanBerker** [comment]
This issue has been addressed:
`jiqs$ count(json-file("./src/main/resources/queries/confusion_sample.json").choices[])`

2000

**Dummy query showing warning message:**
```
jiqs$ for $i in parallelize(1 to 500)
return 1

```
Warning: Results have been truncated to: 100 items. This value can be configured with the --result-size parameter at startup.

(1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1)
[EXEC TIME]: 125

**Comment by ghislainfourny** [comment]
Thanks!
