### ISSUE TITLE
Filtering using predicates ([ ]) always only returns the last matching item

### ISSUE THREAD

**Issue by rschoening** [Sparksoniq/sparksoniq#140]
Example:
`{ "digits" : (0 to 3)[$$ gt 1] }`
returns 
`{ "digits" : 3 }`

expected: 
`{ "digits" : [ 2, 3 ] }`

regardless of predicate used (also for `[true]`).
Same behavior when applied to file ( `json-file("...")[true]`)

Workaround: rewrite as FLWOR/`where` expression

**Comment by ghislainfourny** [comment]
Many thanks for raising this. Indeed, this is a bug. We will address it.
