### ISSUE TITLE
Bug with if-then-else

### ISSUE THREAD

**Issue by ghislainfourny** [Sparksoniq/sparksoniq#15]
for $x in 1 to 10
    return if ($x lt 5) then $x
                   else -$x

This returns an error

[ERROR] Job aborted due to stage failure: Task 0 in stage 10.0 failed 1 times, most recent failure: Lost task 0.0 in stage 10.0 (TID 10, localhost, executor driver): sparksoniq.exceptions.IteratorFlowException: Error [err: XPDY0130]Invalid next() call; If expr

**Comment by wscsprint3r** [comment]
Fixed version: https://github.com/Sparksoniq/sparksoniq/pull/26/commits/18624922223366def2c8878897ea8ef2d83b384d
