### ISSUE TITLE
Parsing fails

### ISSUE THREAD

**Issue by ghislainfourny** [Sparksoniq/sparksoniq#17]
let $person := {
  "name" : "Sarah",
  "age" : 13,
  "gender" : "female",
  "friends" : [ "Jim", "Mary", "Jennifer"]
}
return { "how many friends" : size($person.friends)) }

**Comment by CanBerker** [comment]
I think there is a type with the above query: size has 2 closing parenthesis. When one is removed the query is of the form:
let $person := {
"name" : "Sarah",
"age" : 13,
"gender" : "female",
"friends" : [ "Jim", "Mary", "Jennifer"]
}
return { "how many friends" : size($person.friends) }

And result is:
{ "how many friends" : 3 }

Is that correct or is there something that I'm missing?

**Comment by ghislainfourny** [comment]
Very good catch, Can. That was indeed a typo in the tutorial.

It would be nice if you could double-check that the right error code is returned with the extra parenthesis (i.e., a nice parser error). Then we can close this bug.

**Comment by CanBerker** [comment]
The error returned is below:

jiqs$ let $person := {
>>> "name" : "Sarah",
>>> "age" : 13,
>>> "gender" : "female",
>>> "friends" : [ "Jim", "Mary", "Jennifer"]
>>> }
>>> return { "how many friends" : size($person.friends)) }
>>> 
>>> 
[ERROR] Error [err: XPST0003]LINE:7:COLUMN:52:Parser failed. )
