### ISSUE TITLE
Remove getNewRDDFromExpression in forClause

### ISSUE THREAD

**Issue by CanBerker** [Sparksoniq/sparksoniq#176]
Postponed until all local clauses are implemented.

I think that can even be simplified, because the else case in getNewRDDFromExpression will never happen (it is now handled with the newly implemented local execution). So you can directly ask for the expression RDD here and remove that function.

_Originally posted by @ghislainfourny in https://github.com/Sparksoniq/sparksoniq/pull/174/files_

**Comment by ghislainfourny** [comment]
@CanBerker Is this issue now taken care of?

**Comment by CanBerker** [comment]
Yes exactly, closing the issue now
