### ISSUE TITLE
Object lookup only returns value of first object

### ISSUE THREAD

**Issue by ghislainfourny** [Sparksoniq/sparksoniq#21]
({"foo" : "bar"}, {"foo" : "foobar"}).foo

only returns "bar"
but should return the sequence "bar", "foobar"

Likewise,

    ().foo

should return the empty sequence and currently returns an error.

**Comment by CanBerker** [comment]
Issue solved in PR:
https://github.com/Sparksoniq/sparksoniq/pull/45
