### ISSUE TITLE
Mark some dependencies as "provided" or "test" to reduce size

### ISSUE THREAD

**Issue by ghislainfourny** [Sparksoniq/sparksoniq#22]
As documented here:

https://spark.apache.org/docs/latest/submitting-applications.html

Spark and Hadoop can be marked as "provided", which will remove them from the jar as the classes will be in scope at runtime.

Likewise, test dependencies can be marked as "test".

**Comment by wscsprint3r** [comment]
Size of jar has been reduced from 90MB to ~2MB. 

Fix version: https://github.com/Sparksoniq/sparksoniq/pull/26/commits/8288a8c5a62ed6322f72a81899497fe69b2cce04
