### ISSUE TITLE
Top-level arithmetic expression returns result of first FLOWR expression

### ISSUE THREAD

**Issue by ingomueller-net** [Sparksoniq/sparksoniq#88]
The following query (run against the language game dataset) produces the wrong result:

    (for $o in json-file("wasb:///sample.json")
    where $o.choices[[1]] = $o.target
    return $o) div count(json-file("wasb:///sample.json")))

I am not sure what it should do (I forgot to call count on the result of the first FLOWR expression), but I think it should do what it does, namely return the result of the first FLOWR expression.

**Comment by ingomueller-net** [comment]
Aha, I am looking at my traces again. One of the runs returned the following error:

    [ERROR] Error [err: XPTY0004]LINE:1:COLUMN:0:Multiplicative expression has non numeric args { "date" : "2013-08-19", "country" : "AU", "guess" : "German", "choices" : [ German, Serbian, Swedish, Vietnamese ], "sample" : "e77d97b712adffc39e531e20237a5589", "target" : "German" }, 100

Is this what should happen? Maybe everything is working as it should then...

**Comment by ghislainfourny** [comment]
You are attempting to divide a sequence of objects by an integer -- the error is thus correctly reported as a type error. Do you agree?

**Comment by ingomueller-net** [comment]
Yes. I didn't read the message properly (and I was confused by a different message).
