### ISSUE TITLE
Error returned instead of returning empty sequence

### ISSUE THREAD

**Issue by ingomueller-net** [Sparksoniq/sparksoniq#89]
The following query (where array access ``[[0]]`` is mistakenly written as array constructor `[0]`) causes a job abortion:

    jiqs$ for $o in json-file("wasb:///sample.json")
    >>> where $o.choices[0] eq $o.target
    >>> return $o
    >>>
    >>>
    [ERROR] Job aborted due to stage failure: Task 0 in stage 25.0 failed 4 times, most recent failure: Lost task 0.3 in stage 25.0 (TID 29, wn0-testsp.mjhvh3c1nveurdkkutux1zeupg.cx.internal.cloudapp.net, executor 2): sparksoniq.exceptions.IteratorFlowException: Error [err: XPDY0130]LINE:2:COLUMN:6:Invalid next() call;

I guess a syntax error (or at least some more high-level error) would be more appropriate.

**Comment by ghislainfourny** [comment]
Thanks, Ingo.

This is not a syntax error. [0] filters for a position, but positions start at 1, so $o.choices[0] should return an empty sequence. Then, eq returns () as well and where should be false, so the overall query should return ().

But there is indeed a bug in our iterators that we need to fix.

FYI if you need the first choice, then the syntax for this should be

$o.choices[[1]]

(array lookup is [[ ]], and positions start at 1 in JSONiq).

**Comment by ingomueller-net** [comment]
OK, I think I understand the difference now. So, as you say, it's only the problem with the iterator.

**Comment by ghislainfourny** [comment]
I am happy to announce that this is now solved :)
