### ISSUE TITLE
Issue with nested Spark actions

### ISSUE THREAD

**Issue by ghislainfourny** [Sparksoniq/sparksoniq#92]
let $p := count(
  for $i in json-file("hdfs:///data/small.json")
  where $i.guess=$i.choices[[1]] and $i.guess=$i.target
  return $i)
let $t := count(
  for $j in json-file("hdfs:///data/small.json")
  where $j.guess=$j.choices[[1]]
  return $j)
return {"res": ($p+0.0) div $t}

Job aborts because of stage failure.

**Comment by CanBerker** [comment]
jiqs$ let $p := count(
>>> for $i in json-file("./src/main/resources/queries/confusion_sample.json")
>>> where $i.guess=$i.choices[[1]] and $i.guess=$i.target
>>> return $i)
>>> let $t := count(
>>> for $j in json-file("./src/main/resources/queries/confusion_sample.json")
>>> where $j.guess=$j.choices[[1]]
>>> return $j)
>>> return {"res": ($p+0.0) div $t}
>>> 
>>> 
{ "res" : 0.5862068966 }

After recent developments, the query (slightly modified file location) gives the above results.

**Comment by ghislainfourny** [comment]
Wonderful! :-) Thank you for double-checking, Can.
