### ISSUE TITLE
Report missing function correctly

### ISSUE THREAD

**Issue by ingomueller-net** [Sparksoniq/sparksoniq#93]
If a function doesn't exist, the current error message is misleading. I do not have a cluster running at the moment, so I can't copy the output, but it is along the lines of "The function has the wrong arity." Instead, it should say something like "The function does not exist."

**Comment by dimkou** [comment]
This is the full error
```
[ERROR] Error [err: XPST0017]LINE:1:COLUMN:0:Static error; The expanded QName and number of arguments in a static function call do not match the name and arity of a function signature in the static context.
```

**Comment by ghislainfourny** [comment]
Very good point, thanks! We need to explicitly say which function and with which arity wasn't found.

**Comment by ghislainfourny** [comment]
@CanBerker can we close?
