### ISSUE TITLE
Support FLWOR count clauses with zipWithIndex()

### ISSUE THREAD

**Issue by ingomueller-net** [Sparksoniq/sparksoniq#95]
If I understand correctly, `count` clauses are not supported in the outer-most FLOWR expression. I think that there is actually a relatively easy way to get a trivial implementation for it, namely using Spark's [`zipWithIndex`](https://spark.apache.org/docs/2.1.1/api/java/org/apache/spark/rdd/RDD.html#zipWithIndex()). I do not urgently need this feature now, but I want to be sure that this idea doesn't get lost.

**Comment by wscsprint3r** [comment]
I can look into this a bit more.

**Comment by ghislainfourny** [comment]
@wscsprint3r  this is done, right? We could close this issue.
